# Generated by Django 5.2.6 on 2025-12-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('ward', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_on', models.DateTimeField(auto_now_add=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharged_on', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'ADMITTED'), ('discharged', 'DISCHARGED'), ('transferred', 'TRANSFERRED')], default='admitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_admitted', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='patients.patientprofile')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ward.ward')),
            ],
            options={
                'ordering': ['-admitted_on'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Details of the treatment or procedure performed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('procedure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medication_prescribed', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='admmit_treatements.admission')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
