# Generated by Django 5.2.6 on 2025-12-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admmit_treatements', '0001_initial'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='ward.ward'),
        ),
    ]
