# Generated by Django 5.2.6 on 2025-12-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admmit_treatements', '0002_alter_admission_ward'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='ward.bed'),
        ),
    ]
