# Generated by Django 5.2.6 on 2025-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='years_of_experince',
            field=models.BigIntegerField(default=0),
        ),
    ]
