"""
Django settings for odiche_hmsproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    #'accounts',
    'accounts.apps.AccountsConfig',
    'doctors',
    'hospitaladmin',
    #'mainadmin',
    'nurses',
    'patients',
    #'permissions',
   'permissions.apps.PermissionsConfig',
    'pharmacycashiers',
    'pharmarcist',
    'receptionists',
    'accountant',
    'lab_technician',
    'shift_mgt',
    "admmit_treatements",
    'ward',
    'rest_framework.authtoken',
    'utilsapp',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'appointment',
    'medical',
    'lab',
]
    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS =[
    'http://127.0.0.1:5500'
]

ROOT_URLCONF = 'odiche_hmsproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odiche_hmsproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


#TIME_ZONE = 'UTC'
#Switching time Zone to WAT(West African Time) isntead of UTC
TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'



# POSTGRE DATABASE 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # Or 'django.db.backends.sqlite3'
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT', cast=int),
#     }
# }


#TEsting using Email console.......will be change latter

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')

# OTP Configuration
OTP_TTL_SECONDS = config("OTP_TTL_SECONDS", cast=int, default=1200)
HUMAN_TTL = config("HUMAN_TTL", default="20 minutes")



"""
setting up celery for and redis cashsing
this enables storing of the otp password using CELERY CACHES
without nedding to create a database model for storing of opt token
generated
"""


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',
        'OPTIONS': {
            #'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# OTP:904611 for  example@gmail.com
#admin details;
#admin@gmail.com: password:admin

# { For testing details 
#   "email": "example@gmail.com",
#   "first_name": "udoka",
#   "last_name": "ubong",
#   "role": "doctor",
#   "state": "Abia"
# }
#use this command to start celery;

# celery -A odiche_hmsproject worker -l info

#use this instead to start the celery:
# celery -A odiche_hmsproject worker -l info --pool=solo
#To start redis use this;
# redis-server.exe


#redis-server.exe --port 6379 

#Testing email sending using shell;
"""
from django.core.mail import send_mail

send_mail(
    subject='OTP Test',
    message='This is a test email from your Django app.',
    from_email='umichaelmichael@gmail.com',
    recipient_list=['udokaubong08@gmail.com'],
    fail_silently=False,
)
"""


#setting up jwt token set up for roles permissions
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),   # short-lived token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),      # refresh token
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),  # e.g. "Authorization: Bearer <token>"
}

# REST_FRAMEWORK = {
#     # ... your other DRF settings
    
# }
# Email settings for development
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "noreply@medsys.com"



#email/OTP setup

#Email for production
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"  
# EMAIL_PORT = 587  
# EMAIL_USE_TLS = True 
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = "umichaelmichael@gmail.com"
# EMAIL_HOST_PASSWORD = "ccmmjwqilzlvxntz" #old hostpassword

#Use to delete all already created users using shell:
# from accounts.models import CustomUser
# CustomUser.objects.all().delete()
# To delete a specific user use this
#CustomUser.objects.filter(email="example@email.com").delete()

FRONTEND_URL = "http://localhost:3000"