# Generated by Django 5.2.6 on 2025-12-05 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
        ('shift_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='shift',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_mgt.shift'),
        ),
    ]
