# Generated by Django 5.2.6 on 2025-11-27 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('main_admin', 'MAIN ADMIN'), ('hospital_admin', 'HOSPITAL ADMIN'), ('doctor', 'DOCTOR'), ('nurse', 'NURSE'), ('accountant', 'ACCOUNTANT'), ('pharmacist', 'PHARMACIST'), ('pharmacy_cashier', 'PHARMACY CASHIER'), ('lab_technician', 'LAB TECHNICIAN'), ('receptionist', 'RECEPTIONIST'), ('patient', 'PATIENT')], max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('user', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
