# Generated by Django 5.2.6 on 2025-12-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
    ]
