# Generated by Django 5.2.6 on 2025-11-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('shift_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_mgt.shift'),
        ),
    ]
