# Generated by Django 5.2.6 on 2025-11-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0002_doctor_shift'),
        ('shift_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialization', models.CharField(choices=[('general_practitioner', 'General Practitioner'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('surgeon', 'Surgeon'), ('radiologist', 'Radiologist'), ('orthopedic', 'Orthopedic'), ('gynecologist', 'Gynecologist'), ('other', 'Other')], max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('available_time_from', models.TimeField(blank=True, null=True)),
                ('available_time_to', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_mgt.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
