# Generated by Django 5.2.6 on 2025-12-17 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shift_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCashierProfile',
            fields=[
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cashier_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_process_payments', models.BooleanField(default=True)),
                ('can_verify_prescriptions', models.BooleanField(default=True)),
                ('shift', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_mgt.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
